"""baseline postgresql

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 03:03:29.902161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ENUM_TYPES = ("subscriptionstatus", "userrole", "tourstatus", "paymentfrequency", "loanstatus", "paymenttype")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('customer_limit', sa.Integer(), nullable=False),
    sa.Column('loan_limit', sa.Integer(), nullable=False),
    sa.Column('user_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_price_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('paypal_plan_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paypal_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_companies_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('account_number', sa.String(length=60), nullable=False),
    sa.Column('account_holder', sa.String(length=140), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bank_accounts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts'))
    )
    op.create_index(op.f('ix_bank_accounts_company_id'), 'bank_accounts', ['company_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('manager_name', sa.String(length=140), nullable=False),
    sa.Column('notary_name', sa.String(length=140), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=60), server_default='', nullable=False),
    sa.Column('municipality', sa.String(length=80), server_default='', nullable=False),
    sa.Column('sector', sa.String(length=120), server_default='', nullable=False),
    sa.Column('street', sa.String(length=160), server_default='', nullable=False),
    sa.Column('house_number', sa.String(length=40), server_default='', nullable=False),
    sa.Column('address_reference', sa.String(length=255), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_settings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings'))
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=True)
    op.create_table('loan_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('minimum_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_term_count', sa.Integer(), nullable=False),
    sa.Column('minimum_term_unit', sa.String(length=20), nullable=False),
    sa.Column('default_late_fee_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_grace_days', sa.Integer(), nullable=False),
    sa.Column('require_route_assignment', sa.Boolean(), nullable=False),
    sa.Column('allow_payment_date_change', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_loan_settings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_settings'))
    )
    op.create_index(op.f('ix_loan_settings_company_id'), 'loan_settings', ['company_id'], unique=True)
    op.create_table('print_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('enable_receipts', sa.Boolean(), nullable=False),
    sa.Column('enable_promissory_note', sa.Boolean(), nullable=False),
    sa.Column('show_tax_id', sa.Boolean(), nullable=False),
    sa.Column('show_document_id', sa.Boolean(), nullable=False),
    sa.Column('show_phone', sa.Boolean(), nullable=False),
    sa.Column('allow_share_receipt', sa.Boolean(), nullable=False),
    sa.Column('enable_invoice_printing', sa.Boolean(), nullable=False),
    sa.Column('receipt_footer_text', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_print_settings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_settings'))
    )
    op.create_index(op.f('ix_print_settings_company_id'), 'print_settings', ['company_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'failed', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_subscriptions_company_id_companies')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_company_id'), 'subscriptions', ['company_id'], unique=False)
    op.create_table('cash_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cash_boxes_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cash_boxes_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_boxes')),
    sa.UniqueConstraint('branch_id', name=op.f('uq_cash_boxes_branch_id'))
    )
    op.create_index(op.f('ix_cash_boxes_company_id'), 'cash_boxes', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'manager', 'collector', 'cashier', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('last_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cash_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_cash_audit_actor_id_users')),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_audit_box_id_cash_boxes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_audit'))
    )
    op.create_index(op.f('ix_cash_audit_box_id'), 'cash_audit', ['box_id'], unique=False)
    op.create_table('cash_configs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name=op.f('fk_cash_configs_activated_by_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cash_configs_company_id_companies')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_cash_configs'))
    )
    op.create_table('cash_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_cash_requests_actor_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cash_requests_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_requests')),
    sa.UniqueConstraint('company_id', 'actor_id', 'key', name=op.f('uq_cash_requests_company_id'))
    )
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('opening_expected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opening_counted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('denominations', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_sessions_box_id_cash_boxes')),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], name='fk_cash_sessions_cashier_id'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_cash_sessions_closed_by_users')),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], name=op.f('fk_cash_sessions_opened_by_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_cash_sessions_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_sessions'))
    )
    op.create_index(op.f('ix_cash_sessions_box_id'), 'cash_sessions', ['box_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_cashier_id'), 'cash_sessions', ['cashier_id'], unique=False)
    op.create_table('location_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_location_pings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_pings'))
    )
    op.create_index(op.f('ix_location_pings_recorded_at'), 'location_pings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_pings_user_id'), 'location_pings', ['user_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_codes'))
    )
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.create_table('payroll_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salary_frequency', sa.String(length=20), nullable=False),
    sa.Column('commissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_configs_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payroll_configs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_configs'))
    )
    op.create_index(op.f('ix_payroll_configs_company_id'), 'payroll_configs', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_configs_user_id'), 'payroll_configs', ['user_id'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('assigned_collector_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('boundary', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_collector_id'], ['users.id'], name=op.f('fk_routes_assigned_collector_id_users')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_routes_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_routes_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_assigned_collector_id'), 'routes', ['assigned_collector_id'], unique=False)
    op.create_index(op.f('ix_routes_branch_id'), 'routes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_routes_company_id'), 'routes', ['company_id'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_table('tour_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'skipped', name='tourstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('tour_version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tour_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_progress')),
    sa.UniqueConstraint('user_id', 'tour_id', name='uq_tour_progress_user_tour')
    )
    op.create_index(op.f('ix_tour_progress_user_id'), 'tour_progress', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('cash_custody_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('acceptance_id', sa.String(length=80), nullable=True),
    sa.Column('acceptance_method', sa.String(length=40), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('capital_movement_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name=op.f('fk_cash_custody_transfers_accepted_by_users')),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_custody_transfers_box_id_cash_boxes')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cash_custody_transfers_company_id_companies')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_cash_custody_transfers_from_user_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('fk_cash_custody_transfers_session_id_cash_sessions')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_cash_custody_transfers_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_custody_transfers')),
    sa.UniqueConstraint('acceptance_id', name=op.f('uq_cash_custody_transfers_acceptance_id')),
    sa.UniqueConstraint('capital_movement_id', name=op.f('uq_cash_custody_transfers_capital_movement_id')),
    sa.UniqueConstraint('cash_movement_id', name=op.f('uq_cash_custody_transfers_cash_movement_id'))
    )
    op.create_index(op.f('ix_cash_custody_transfers_box_id'), 'cash_custody_transfers', ['box_id'], unique=False)
    op.create_index(op.f('ix_cash_custody_transfers_company_id'), 'cash_custody_transfers', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_custody_transfers_session_id'), 'cash_custody_transfers', ['session_id'], unique=False)
    op.create_table('cash_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('declared', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remaining', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_deliveries_box_id_cash_boxes')),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], name=op.f('fk_cash_deliveries_cashier_id_users')),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_cash_deliveries_collector_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('fk_cash_deliveries_session_id_cash_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_deliveries'))
    )
    op.create_index(op.f('ix_cash_deliveries_box_id'), 'cash_deliveries', ['box_id'], unique=False)
    op.create_index(op.f('ix_cash_deliveries_collector_id'), 'cash_deliveries', ['collector_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('document_id', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('calle', sa.String(length=120), nullable=True),
    sa.Column('barrio', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('house_number', sa.String(length=60), nullable=True),
    sa.Column('building', sa.String(length=160), nullable=True),
    sa.Column('apartment', sa.String(length=60), nullable=True),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_key', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('home_phone', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('references', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_collector_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cash_branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_collector_id'], ['users.id'], name=op.f('fk_customers_assigned_collector_id_users')),
    sa.ForeignKeyConstraint(['cash_branch_id'], ['branches.id'], name=op.f('fk_customers_cash_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customers_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_customers_created_by_id_users')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_customers_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('company_id', 'document_key', name='uq_customer_company_document')
    )
    op.create_index(op.f('ix_customers_assigned_collector_id'), 'customers', ['assigned_collector_id'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_route_id'), 'customers', ['route_id'], unique=False)
    op.create_table('route_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('area_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_areas_route_id_routes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_areas'))
    )
    op.create_index(op.f('ix_route_areas_normalized_name'), 'route_areas', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_route_areas_route_id'), 'route_areas', ['route_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('late_fee_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('daily', 'weekly', 'biweekly', 'monthly', name='paymentfrequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('principal_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'paid', 'late', 'cancelled', name='loanstatus'), nullable=False),
    sa.Column('route_name', sa.String(length=40), nullable=True),
    sa.Column('requires_promissory_note', sa.Boolean(), nullable=False),
    sa.Column('cash_branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cash_branch_id'], ['branches.id'], name=op.f('fk_loans_cash_branch_id_branches')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_loans_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_loans_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_index(op.f('ix_loans_customer_id'), 'loans', ['customer_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_version', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_loan_applications_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_loan_applications_created_by_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_loan_applications_customer_id_customers')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_applications_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_applications')),
    sa.UniqueConstraint('loan_id', name=op.f('uq_loan_applications_loan_id'))
    )
    op.create_index(op.f('ix_loan_applications_company_id'), 'loan_applications', ['company_id'], unique=False)
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_installments_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_installments'))
    )
    op.create_index(op.f('ix_loan_installments_loan_id'), 'loan_installments', ['loan_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('collected_by_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('installment', 'payoff', 'custom', 'principal_only', 'interest_only', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('cash_state', sa.String(length=20), server_default='historical', nullable=False),
    sa.Column('reference_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payments_branch_id_branches')),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], name=op.f('fk_payments_collected_by_id_users')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_payments_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payments_loan_id'), 'payments', ['loan_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('media_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], name=op.f('fk_application_documents_application_id_loan_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_documents'))
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_table('cash_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['cash_deliveries.id'], name=op.f('fk_cash_allocations_delivery_id_cash_deliveries')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_cash_allocations_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_allocations')),
    sa.UniqueConstraint('delivery_id', 'payment_id', name=op.f('uq_cash_allocations_delivery_id'))
    )
    op.create_index(op.f('ix_cash_allocations_payment_id'), 'cash_allocations', ['payment_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('custody_transfer_id', sa.Integer(), nullable=True),
    sa.Column('reverses_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('proof', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_cash_movements_actor_id_users')),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_movements_box_id_cash_boxes')),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_cash_movements_collector_id_users')),
    sa.ForeignKeyConstraint(['custody_transfer_id'], ['cash_custody_transfers.id'], name='fk_cash_movements_custody_transfer_id'),
    sa.ForeignKeyConstraint(['delivery_id'], ['cash_deliveries.id'], name=op.f('fk_cash_movements_delivery_id_cash_deliveries')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_cash_movements_loan_id_loans')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_cash_movements_payment_id_payments')),
    sa.ForeignKeyConstraint(['reverses_id'], ['cash_movements.id'], name=op.f('fk_cash_movements_reverses_id_cash_movements')),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], name=op.f('fk_cash_movements_session_id_cash_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_movements')),
    sa.UniqueConstraint('reverses_id', name=op.f('uq_cash_movements_reverses_id'))
    )
    op.create_index(op.f('ix_cash_movements_box_id'), 'cash_movements', ['box_id'], unique=False)
    op.create_table('cash_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('proof', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_cash_transfers_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['box_id'], ['cash_boxes.id'], name=op.f('fk_cash_transfers_box_id_cash_boxes')),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_cash_transfers_collector_id_users')),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_cash_transfers_loan_id_loans')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_cash_transfers_payment_id_payments')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_cash_transfers_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_transfers')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_cash_transfers_payment_id'))
    )
    op.create_index(op.f('ix_cash_transfers_box_id'), 'cash_transfers', ['box_id'], unique=False)
    op.create_table('capital_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_capital_movements_actor_id_users')),
    sa.ForeignKeyConstraint(['cash_movement_id'], ['cash_movements.id'], name=op.f('fk_capital_movements_cash_movement_id_cash_movements')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_capital_movements_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capital_movements')),
    sa.UniqueConstraint('cash_movement_id', name='uq_capital_movements_cash_movement_id')
    )
    op.create_index(op.f('ix_capital_movements_company_id'), 'capital_movements', ['company_id'], unique=False)
    op.create_table('payroll_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('salary_part', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_part', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('capital_movement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_payroll_payments_actor_id_users')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payroll_payments_branch_id_branches')),
    sa.ForeignKeyConstraint(['capital_movement_id'], ['capital_movements.id'], name=op.f('fk_payroll_payments_capital_movement_id_capital_movements')),
    sa.ForeignKeyConstraint(['cash_movement_id'], ['cash_movements.id'], name=op.f('fk_payroll_payments_cash_movement_id_cash_movements')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payroll_payments_company_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payroll_payments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_payments'))
    )
    op.create_index(op.f('ix_payroll_payments_company_id'), 'payroll_payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_payments_user_id'), 'payroll_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_payments_user_id'), table_name='payroll_payments')
    op.drop_index(op.f('ix_payroll_payments_company_id'), table_name='payroll_payments')
    op.drop_table('payroll_payments')
    op.drop_index(op.f('ix_capital_movements_company_id'), table_name='capital_movements')
    op.drop_table('capital_movements')
    op.drop_index(op.f('ix_cash_transfers_box_id'), table_name='cash_transfers')
    op.drop_table('cash_transfers')
    op.drop_index(op.f('ix_cash_movements_box_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_allocations_payment_id'), table_name='cash_allocations')
    op.drop_table('cash_allocations')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_payments_loan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_loan_installments_loan_id'), table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_index(op.f('ix_loan_applications_company_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_loans_customer_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_route_areas_route_id'), table_name='route_areas')
    op.drop_index(op.f('ix_route_areas_normalized_name'), table_name='route_areas')
    op.drop_table('route_areas')
    op.drop_index(op.f('ix_customers_route_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_collector_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cash_deliveries_collector_id'), table_name='cash_deliveries')
    op.drop_index(op.f('ix_cash_deliveries_box_id'), table_name='cash_deliveries')
    op.drop_table('cash_deliveries')
    op.drop_index(op.f('ix_cash_custody_transfers_session_id'), table_name='cash_custody_transfers')
    op.drop_index(op.f('ix_cash_custody_transfers_company_id'), table_name='cash_custody_transfers')
    op.drop_index(op.f('ix_cash_custody_transfers_box_id'), table_name='cash_custody_transfers')
    op.drop_table('cash_custody_transfers')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tour_progress_user_id'), table_name='tour_progress')
    op.drop_table('tour_progress')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_company_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_branch_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_assigned_collector_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_payroll_configs_user_id'), table_name='payroll_configs')
    op.drop_index(op.f('ix_payroll_configs_company_id'), table_name='payroll_configs')
    op.drop_table('payroll_configs')
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index(op.f('ix_location_pings_user_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_recorded_at'), table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_cash_sessions_cashier_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_box_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    op.drop_table('cash_requests')
    op.drop_table('cash_configs')
    op.drop_index(op.f('ix_cash_audit_box_id'), table_name='cash_audit')
    op.drop_table('cash_audit')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cash_boxes_company_id'), table_name='cash_boxes')
    op.drop_table('cash_boxes')
    op.drop_index(op.f('ix_subscriptions_company_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_print_settings_company_id'), table_name='print_settings')
    op.drop_table('print_settings')
    op.drop_index(op.f('ix_loan_settings_company_id'), table_name='loan_settings')
    op.drop_table('loan_settings')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_bank_accounts_company_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
    # PostgreSQL keeps ENUM types after their tables are dropped; remove them for a clean downgrade.
    bind = op.get_bind()
    for name in ENUM_TYPES:
        sa.Enum(name=name).drop(bind, checkfirst=True)
