"""identity and authorization foundation

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 09:44:05.062896

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (code, scope_kind, description, is_sensitive)
PERMISSION_CATALOG = [
    ("users.read", "tenant", "Consultar usuarios de la agencia", False),
    ("users.create", "tenant", "Crear usuarios (invitacion de activacion)", True),
    ("users.disable", "tenant", "Desactivar usuarios", True),
    ("users.enable", "tenant", "Reactivar usuarios", True),
    ("roles.read", "tenant", "Consultar roles", False),
    ("roles.create", "tenant", "Crear roles", True),
    ("roles.assign", "tenant", "Asignar y quitar roles a usuarios", True),
    ("permissions.read", "tenant", "Consultar el catalogo de permisos", False),
    ("security.sessions.revoke", "tenant", "Revocar sesiones de un usuario", True),
    ("security.events.read", "tenant", "Consultar eventos de seguridad", False),
    ("platform.users.read", "platform", "Consultar usuarios de plataforma", False),
    ("platform.users.disable", "platform", "Desactivar usuarios de plataforma", True),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_throttle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_throttle')),
    sa.UniqueConstraint('scope', 'key_hash', name=op.f('uq_auth_throttle_scope'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('scope_kind', sa.String(length=10), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope_kind IN ('platform', 'tenant')", name=op.f('ck_permissions_scope_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index('ix_security_events_subject', 'security_events', ['subject_id'], unique=False)
    op.create_index('ix_security_events_tenant_occurred', 'security_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('given_names', sa.String(length=120), nullable=False),
    sa.Column('family_names', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_persons_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_persons_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index('ix_persons_tenant_id', 'persons', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('system_defined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_roles_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_roles_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index('uq_roles_platform_name', 'roles', ['name'], unique=True, postgresql_where=sa.text('tenant_id IS NULL'))
    op.create_index('uq_roles_tenant_name', 'roles', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('tenant_id IS NOT NULL'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('recovery_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('recovery', 'activation')", name=op.f('ck_recovery_tokens_purpose_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_recovery_tokens_created_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_recovery_tokens_token_hash'))
    )
    op.create_index(op.f('ix_recovery_tokens_user_id'), 'recovery_tokens', ['user_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_kind', sa.String(length=10), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(scope_kind = 'branch') = (branch_id IS NOT NULL)", name=op.f('ck_user_role_assignments_branch_scope_consistent')),
    sa.CheckConstraint("scope_kind IN ('tenant', 'branch', 'own')", name=op.f('ck_user_role_assignments_scope_kind_valid')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_role_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_user_role_assignments_branch_id_branches')),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_user_role_assignments_revoked_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_assignments_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_user_role_assignments_tenant_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role_assignments'))
    )
    op.create_index(op.f('ix_user_role_assignments_role_id'), 'user_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_tenant_id'), 'user_role_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_index('uq_assignment_active_branch', 'user_role_assignments', ['user_id', 'role_id', 'branch_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL AND branch_id IS NOT NULL'))
    op.create_index('uq_assignment_active_nonbranch', 'user_role_assignments', ['user_id', 'role_id', 'scope_kind'], unique=True, postgresql_where=sa.text('revoked_at IS NULL AND branch_id IS NULL'))
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('revoked_reason', sa.String(length=40), nullable=True))
    op.add_column('user_sessions', sa.Column('created_ip', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('person_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('superadmin', 'admin', 'manager', 'collector', 'cashier', name='userrole'),
               nullable=True)
    op.create_index(op.f('ix_users_person_id'), 'users', ['person_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_person_id_persons'), 'users', 'persons', ['person_id'], ['id'])
    # Backfill from the legacy flag, then retire it (``status`` is authoritative; RESET_AND_RESEED data only).
    op.execute("UPDATE users SET status = CASE WHEN is_active THEN 'active' ELSE 'disabled' END, "
               "activated_at = created_at, disabled_at = CASE WHEN is_active THEN NULL ELSE now() END")
    op.alter_column('users', 'status', server_default=None)
    op.alter_column('users', 'updated_at', server_default=None)
    op.drop_column('users', 'is_active')
    op.create_check_constraint('status_valid', 'users', "status IN ('pending', 'active', 'locked', 'disabled')")

    # security_events is append-only evidence: reject UPDATE/DELETE at the database level.
    op.execute("""
        CREATE FUNCTION security_events_immutable() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'security_events is append-only';
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("CREATE TRIGGER trg_security_events_immutable BEFORE UPDATE OR DELETE ON security_events "
               "FOR EACH ROW EXECUTE FUNCTION security_events_immutable()")

    # Permission catalogue as of T-002 (later packages add theirs in their own migrations).
    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": k, "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, k, d, x in PERMISSION_CATALOG
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_status_valid'), 'users', type_='check')
    op.execute("DROP TRIGGER IF EXISTS trg_security_events_immutable ON security_events")
    op.execute("DROP FUNCTION IF EXISTS security_events_immutable()")
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False, server_default=sa.true()))
    op.execute("UPDATE users SET is_active = (status = 'active'), role = COALESCE(role, 'collector')")
    op.alter_column('users', 'is_active', server_default=None)
    op.drop_constraint(op.f('fk_users_person_id_persons'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_person_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('superadmin', 'admin', 'manager', 'collector', 'cashier', name='userrole'),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'disabled_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'locked_at')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'person_id')
    op.drop_column('user_sessions', 'created_ip')
    op.drop_column('user_sessions', 'revoked_reason')
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'expires_at')
    op.create_table('password_reset_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_codes'))
    )
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.drop_index('uq_assignment_active_nonbranch', table_name='user_role_assignments', postgresql_where=sa.text('revoked_at IS NULL AND branch_id IS NULL'))
    op.drop_index('uq_assignment_active_branch', table_name='user_role_assignments', postgresql_where=sa.text('revoked_at IS NULL AND branch_id IS NOT NULL'))
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_tenant_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_recovery_tokens_user_id'), table_name='recovery_tokens')
    op.drop_table('recovery_tokens')
    op.drop_table('role_permissions')
    op.drop_index('uq_roles_tenant_name', table_name='roles', postgresql_where=sa.text('tenant_id IS NOT NULL'))
    op.drop_index('uq_roles_platform_name', table_name='roles', postgresql_where=sa.text('tenant_id IS NULL'))
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_persons_tenant_id', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_security_events_tenant_occurred', table_name='security_events')
    op.drop_index('ix_security_events_subject', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('permissions')
    op.drop_table('auth_throttle')
    # ### end Alembic commands ###
