"""tenant aware login identifier

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 10:34:35.910654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('uq_users_platform_email', 'users', ['email'], unique=True, postgresql_where=sa.text('company_id IS NULL'))
    op.create_index('uq_users_tenant_email', 'users', ['company_id', 'email'], unique=True, postgresql_where=sa.text('company_id IS NOT NULL'))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET email = lower(btrim(email))")
    op.create_check_constraint('email_normalized', 'users', 'email = lower(btrim(email))')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_email_normalized'), 'users', type_='check')
    # NOTE: fails if the same email already exists in two tenants (the old model forbade it).
    op.drop_index('uq_users_tenant_email', table_name='users', postgresql_where=sa.text('company_id IS NOT NULL'))
    op.drop_index('uq_users_platform_email', table_name='users', postgresql_where=sa.text('company_id IS NULL'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
