"""tenant slug and external identities

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 10:50:57.597308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('google')", name=op.f('ck_external_identities_provider_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_external_identities_tenant_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities'))
    )
    op.create_index(op.f('ix_external_identities_tenant_id'), 'external_identities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_index('uq_external_identity_active_subject', 'external_identities', ['tenant_id', 'provider', 'issuer', 'subject'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_external_identity_active_user', 'external_identities', ['user_id', 'provider'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('oidc_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('login', 'link')", name=op.f('ck_oidc_challenges_purpose_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_oidc_challenges_tenant_id_companies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oidc_challenges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_challenges')),
    sa.UniqueConstraint('nonce_hash', name=op.f('uq_oidc_challenges_nonce_hash'))
    )
    op.add_column('companies', sa.Column('slug', sa.String(length=63), nullable=True))
    # Existing tenants get a deterministic, unique slug derived from the name plus the id.
    op.execute(
        "UPDATE companies SET slug = COALESCE(NULLIF(trim(both '-' from left(lower("
        "regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')), 48)), ''), 'agencia') || '-' || id"
    )
    op.alter_column('companies', 'slug', nullable=False)
    op.create_unique_constraint(op.f('uq_companies_slug'), 'companies', ['slug'])
    op.create_check_constraint('slug_format', 'companies', "slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_companies_slug_format'), 'companies', type_='check')
    op.drop_constraint(op.f('uq_companies_slug'), 'companies', type_='unique')
    op.drop_column('companies', 'slug')
    op.drop_table('oidc_challenges')
    op.drop_index('uq_external_identity_active_user', table_name='external_identities', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('uq_external_identity_active_subject', table_name='external_identities', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_tenant_id'), table_name='external_identities')
    op.drop_table('external_identities')
    # ### end Alembic commands ###
