"""customer foundation

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 14:48:12.873528

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (code, description, is_sensitive)
NEW_PERMISSIONS = [
    ("customers.read", "Consultar clientes (datos no sensibles)", False),
    ("customers.read_sensitive", "Ver documento de identidad y fecha de nacimiento", True),
    ("customers.create", "Registrar clientes", False),
    ("customers.update", "Editar datos basicos, contactos, direcciones y referencias", False),
    ("customers.identity.correct", "Corregir o cambiar la identidad de un cliente", True),
    ("customers.activate", "Activar y desactivar clientes", True),
    ("customers.assign_branch", "Cambiar la sucursal de gestion de un cliente", True),
    ("customers.duplicates.review", "Revisar posibles duplicados (sin fusionar)", True),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('document_number_normalized', sa.String(length=40), nullable=True))
    op.add_column('persons', sa.Column('document_country', sa.String(length=80), nullable=True))
    op.add_column('persons', sa.Column('document_issue_date', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('document_expiry_date', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('alias', sa.String(length=80), nullable=True))
    op.add_column('persons', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('nationality', sa.String(length=80), nullable=True))
    op.add_column('persons', sa.Column('search_name', sa.String(length=260), nullable=False, server_default=''))
    op.create_index('ix_persons_tenant_search_name', 'persons', ['tenant_id', 'search_name'], unique=False)
    op.create_index('uq_persons_tenant_document', 'persons', ['tenant_id', 'document_type', 'document_number_normalized'], unique=True, postgresql_where=sa.text('tenant_id IS NOT NULL AND document_number_normalized IS NOT NULL'))
    op.create_unique_constraint('uq_persons_tenant_id', 'persons', ['tenant_id', 'id'])
    op.execute("UPDATE persons SET search_name = translate(lower(btrim(given_names || ' ' || family_names)), 'áéíóúüñàèìòù', 'aeiouunaeiou')")
    op.alter_column('persons', 'search_name', server_default=None)
    op.create_check_constraint('document_consistent', 'persons', '(document_number IS NULL) = (document_number_normalized IS NULL)')
    op.create_check_constraint('document_type_required', 'persons', 'document_number IS NULL OR document_type IS NOT NULL')
    op.create_check_constraint('document_dates_ordered', 'persons', 'document_issue_date IS NULL OR document_expiry_date IS NULL OR document_expiry_date >= document_issue_date')
    op.create_table('tenant_sequences',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_tenant_sequences_tenant_id_companies')),
    sa.PrimaryKeyConstraint('tenant_id', 'name', name=op.f('pk_tenant_sequences'))
    )
    op.create_table('person_identity_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('correction', 'change')", name=op.f('ck_person_identity_revisions_kind_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['persons.tenant_id', 'persons.id'], name='fk_person_identity_revisions_tenant_person'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_person_identity_revisions_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_identity_revisions'))
    )
    op.create_index('ix_person_identity_revisions_person', 'person_identity_revisions', ['person_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_branch_id', sa.Integer(), nullable=True),
    sa.Column('management_branch_id', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('internal_note', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('legacy_customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'inactive')", name=op.f('ck_customer_profiles_status_valid')),
    sa.ForeignKeyConstraint(['legacy_customer_id'], ['customers.id'], name=op.f('fk_customer_profiles_legacy_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'management_branch_id'], ['branches.company_id', 'branches.id'], name='fk_customer_profiles_tenant_management_branch'),
    sa.ForeignKeyConstraint(['tenant_id', 'origin_branch_id'], ['branches.company_id', 'branches.id'], name='fk_customer_profiles_tenant_origin_branch'),
    sa.ForeignKeyConstraint(['tenant_id', 'person_id'], ['persons.tenant_id', 'persons.id'], name='fk_customer_profiles_tenant_person'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_customer_profiles_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_profiles')),
    sa.UniqueConstraint('legacy_customer_id', name=op.f('uq_customer_profiles_legacy_customer_id')),
    sa.UniqueConstraint('tenant_id', 'customer_code', name='uq_customer_profiles_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_customer_profiles_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'person_id', name='uq_customer_profiles_tenant_person')
    )
    op.create_index('ix_customer_profiles_tenant_management_branch', 'customer_profiles', ['tenant_id', 'management_branch_id'], unique=False)
    op.create_index('ix_customer_profiles_tenant_status', 'customer_profiles', ['tenant_id', 'status'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('barrio', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=160), nullable=True),
    sa.Column('number', sa.String(length=60), nullable=True),
    sa.Column('building', sa.String(length=160), nullable=True),
    sa.Column('apartment', sa.String(length=60), nullable=True),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactivated_by', sa.Integer(), nullable=True),
    sa.Column('inactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'inactive') = (inactivated_at IS NOT NULL)", name=op.f('ck_customer_addresses_inactivation_consistent')),
    sa.CheckConstraint("NOT is_primary OR status = 'active'", name=op.f('ck_customer_addresses_primary_is_active')),
    sa.CheckConstraint("latitude IS NULL OR coalesce(street, '') <> '' OR coalesce(sector, '') <> '' OR coalesce(barrio, '') <> '' OR coalesce(municipality, '') <> '' OR coalesce(reference_note, '') <> ''", name=op.f('ck_customer_addresses_textual_address_required_with_coordinates')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_customer_addresses_status_valid')),
    sa.CheckConstraint("type IN ('residence', 'work', 'business', 'mailing', 'other')", name=op.f('ck_customer_addresses_type_valid')),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_customer_addresses_coordinates_together')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180', name=op.f('ck_customer_addresses_coordinates_range')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['customer_profiles.tenant_id', 'customer_profiles.id'], name='fk_customer_addresses_tenant_customer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_customer_addresses_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_addresses'))
    )
    op.create_index('ix_customer_addresses_customer', 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('uq_customer_addresses_primary', 'customer_addresses', ['customer_id'], unique=True, postgresql_where=sa.text("is_primary AND status = 'active'"))
    op.create_table('customer_contacts',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactivated_by', sa.Integer(), nullable=True),
    sa.Column('inactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'inactive') = (inactivated_at IS NOT NULL)", name=op.f('ck_customer_contacts_inactivation_consistent')),
    sa.CheckConstraint("NOT is_primary OR status = 'active'", name=op.f('ck_customer_contacts_primary_is_active')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_customer_contacts_status_valid')),
    sa.CheckConstraint("type IN ('phone', 'mobile', 'email', 'other')", name=op.f('ck_customer_contacts_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['customer_profiles.tenant_id', 'customer_profiles.id'], name='fk_customer_contacts_tenant_customer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_customer_contacts_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contacts'))
    )
    op.create_index('ix_customer_contacts_customer', 'customer_contacts', ['customer_id'], unique=False)
    op.create_index('ix_customer_contacts_tenant_normalized', 'customer_contacts', ['tenant_id', 'type', 'normalized_value'], unique=False)
    op.create_index('uq_customer_contacts_primary', 'customer_contacts', ['customer_id', 'type'], unique=True, postgresql_where=sa.text("is_primary AND status = 'active'"))
    op.create_table('customer_duplicate_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_customer_id', sa.Integer(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'dismissed', 'confirmed_duplicate')", name=op.f('ck_customer_duplicate_flags_status_valid')),
    sa.CheckConstraint('customer_id <> candidate_customer_id', name=op.f('ck_customer_duplicate_flags_distinct_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'candidate_customer_id'], ['customer_profiles.tenant_id', 'customer_profiles.id'], name='fk_customer_duplicate_flags_tenant_candidate'),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['customer_profiles.tenant_id', 'customer_profiles.id'], name='fk_customer_duplicate_flags_tenant_customer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_customer_duplicate_flags_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_duplicate_flags')),
    sa.UniqueConstraint('customer_id', 'candidate_customer_id', name='uq_customer_duplicate_flags_pair')
    )
    op.create_index(op.f('ix_customer_duplicate_flags_customer_id'), 'customer_duplicate_flags', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_duplicate_flags_tenant_id'), 'customer_duplicate_flags', ['tenant_id'], unique=False)
    op.create_table('customer_references',
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('relation', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('normalized_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactivated_by', sa.Integer(), nullable=True),
    sa.Column('inactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'inactive') = (inactivated_at IS NOT NULL)", name=op.f('ck_customer_references_inactivation_consistent')),
    sa.CheckConstraint("kind IN ('personal', 'family', 'commercial', 'employer', 'other')", name=op.f('ck_customer_references_kind_valid')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_customer_references_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['customer_profiles.tenant_id', 'customer_profiles.id'], name='fk_customer_references_tenant_customer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_customer_references_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_references'))
    )
    op.create_index('ix_customer_references_customer', 'customer_references', ['customer_id'], unique=False)

    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": "tenant", "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, d, x in NEW_PERMISSIONS
    ])
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("INSERT INTO role_permissions (role_id, permission_id, granted_at) "
               "SELECT r.id, p.id, now() FROM roles r JOIN permissions p ON p.scope_kind = 'tenant' "
               "WHERE r.system_defined AND r.tenant_id IS NOT NULL AND p.code IN (" + codes + ") "
               "ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema (customer data created with the new structures is dropped)."""
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN (" + codes + "))")
    op.execute("DELETE FROM permissions WHERE code IN (" + codes + ")")
    for table in ("customer_references", "customer_duplicate_flags", "customer_contacts", "customer_addresses",
                  "customer_profiles", "person_identity_revisions", "tenant_sequences"):
        op.drop_table(table)
    for name in ("document_dates_ordered", "document_type_required", "document_consistent"):
        op.drop_constraint(op.f("ck_persons_" + name), "persons", type_="check")
    op.drop_constraint("uq_persons_tenant_id", "persons", type_="unique")
    op.drop_index("uq_persons_tenant_document", table_name="persons")
    op.drop_index("ix_persons_tenant_search_name", table_name="persons")
    for column in ("search_name", "nationality", "birth_date", "alias", "document_expiry_date", "document_issue_date",
                   "document_country", "document_number_normalized"):
        op.drop_column("persons", column)
