"""credit product engine

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 16:07:00.001783

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_PERMISSIONS = [
    ("credit.products.read", "Consultar productos de credito, versiones y simulaciones", False),
    ("credit.products.create", "Crear productos de credito", False),
    ("credit.products.update_draft", "Editar y validar borradores de version de producto", False),
    ("credit.products.publish", "Publicar versiones y reactivar productos de credito", True),
    ("credit.products.deactivate", "Desactivar productos y retirar versiones", True),
]
# Immutability guards (kept in sync with app.modules.credit.models; copied so the migration is self-contained)
VERSION_GUARD_FN = "\nCREATE OR REPLACE FUNCTION credit_product_versions_guard() RETURNS trigger AS $$\nBEGIN\n  IF TG_OP = 'DELETE' THEN\n    IF OLD.status <> 'draft' THEN\n      RAISE EXCEPTION 'credit product version % is % and cannot be deleted', OLD.id, OLD.status;\n    END IF;\n    RETURN OLD;\n  END IF;\n  IF OLD.status <> 'draft' THEN\n    IF NEW.id IS DISTINCT FROM OLD.id OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id\n       OR NEW.product_id IS DISTINCT FROM OLD.product_id OR NEW.version_number IS DISTINCT FROM OLD.version_number\n       OR NEW.rules IS DISTINCT FROM OLD.rules OR NEW.rules_hash IS DISTINCT FROM OLD.rules_hash\n       OR NEW.snapshot IS DISTINCT FROM OLD.snapshot OR NEW.effective_from IS DISTINCT FROM OLD.effective_from\n       OR NEW.published_at IS DISTINCT FROM OLD.published_at OR NEW.published_by IS DISTINCT FROM OLD.published_by\n       OR NEW.created_by IS DISTINCT FROM OLD.created_by OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN\n      RAISE EXCEPTION 'credit product version % is published: its rules are immutable', OLD.id;\n    END IF;\n    IF OLD.effective_to IS NOT NULL AND NEW.effective_to IS DISTINCT FROM OLD.effective_to THEN\n      RAISE EXCEPTION 'credit product version % effective_to is already closed', OLD.id;\n    END IF;\n    IF NEW.status <> OLD.status AND NOT (OLD.status = 'published' AND NEW.status = 'retired') THEN\n      RAISE EXCEPTION 'invalid credit product version status transition % -> %', OLD.status, NEW.status;\n    END IF;\n  ELSIF NEW.status NOT IN ('draft', 'published') THEN\n    RAISE EXCEPTION 'a draft version can only become published';\n  END IF;\n  RETURN NEW;\nEND $$ LANGUAGE plpgsql\n"
VERSION_GUARD_TRIGGER = 'CREATE TRIGGER trg_credit_product_versions_guard BEFORE UPDATE OR DELETE ON credit_product_versions FOR EACH ROW EXECUTE FUNCTION credit_product_versions_guard()'
CURRENCY_GUARD_FN = "\nCREATE OR REPLACE FUNCTION credit_product_currencies_guard() RETURNS trigger AS $$\nDECLARE v_old text; v_new text; v_lo integer; v_hi integer;\nBEGIN\n  -- Both ends are checked: a row may not be written into, removed from or MOVED to/from a non-draft version.\n  -- The version rows are locked FOR SHARE (conflicts with publish's FOR UPDATE and with any UPDATE of the\n  -- version) so the draft cannot be published between this check and the commit of the change, and a publish in\n  -- flight makes this write wait and then be rejected. Locks are taken in ascending id order: no lock-order cycles.\n  IF TG_OP = 'INSERT' THEN\n    v_lo := NEW.version_id; v_hi := NEW.version_id;\n  ELSIF TG_OP = 'DELETE' THEN\n    v_lo := OLD.version_id; v_hi := OLD.version_id;\n  ELSE\n    v_lo := LEAST(OLD.version_id, NEW.version_id); v_hi := GREATEST(OLD.version_id, NEW.version_id);\n  END IF;\n  PERFORM 1 FROM credit_product_versions WHERE id = v_lo FOR SHARE;\n  IF v_hi <> v_lo THEN\n    PERFORM 1 FROM credit_product_versions WHERE id = v_hi FOR SHARE;\n  END IF;\n  IF TG_OP IN ('UPDATE', 'DELETE') THEN\n    SELECT status INTO v_old FROM credit_product_versions WHERE id = OLD.version_id;\n  END IF;\n  IF TG_OP IN ('INSERT', 'UPDATE') THEN\n    SELECT status INTO v_new FROM credit_product_versions WHERE id = NEW.version_id;\n  END IF;\n  IF (v_old IS NOT NULL AND v_old <> 'draft') OR (v_new IS NOT NULL AND v_new <> 'draft') THEN\n    RAISE EXCEPTION 'credit product version is published: its currencies are immutable (%)', TG_OP;\n  END IF;\n  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;\nEND $$ LANGUAGE plpgsql\n"
CURRENCY_GUARD_TRIGGER = 'CREATE TRIGGER trg_credit_product_currencies_guard BEFORE INSERT OR UPDATE OR DELETE ON credit_product_currencies FOR EACH ROW EXECUTE FUNCTION credit_product_currencies_guard()'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9][A-Z0-9_-]{1,29}$'", name=op.f('ck_credit_products_code_format')),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive')", name=op.f('ck_credit_products_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_products_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_products')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_credit_products_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_credit_products_tenant_id')
    )
    op.create_index(op.f('ix_credit_products_tenant_id'), 'credit_products', ['tenant_id'], unique=False)
    op.create_table('credit_product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('rules_hash', sa.String(length=80), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_hash', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_by', sa.Integer(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'draft') = (rules_hash IS NULL AND snapshot IS NULL AND effective_from IS NULL AND published_at IS NULL AND published_by IS NULL)", name=op.f('ck_credit_product_versions_publication_consistent')),
    sa.CheckConstraint("(status = 'retired') = (retired_at IS NOT NULL)", name=op.f('ck_credit_product_versions_retirement_consistent')),
    sa.CheckConstraint("status IN ('draft', 'published', 'retired')", name=op.f('ck_credit_product_versions_status_valid')),
    sa.CheckConstraint('effective_to IS NULL OR (effective_from IS NOT NULL AND effective_to >= effective_from)', name=op.f('ck_credit_product_versions_effective_range_ordered')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_credit_product_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'product_id'], ['credit_products.tenant_id', 'credit_products.id'], name='fk_credit_product_versions_tenant_product'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_product_versions_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_product_versions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_credit_product_versions_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'version_number', name='uq_credit_product_versions_number')
    )
    op.create_index('ix_credit_product_versions_product', 'credit_product_versions', ['product_id'], unique=False)
    op.create_index(op.f('ix_credit_product_versions_tenant_id'), 'credit_product_versions', ['tenant_id'], unique=False)
    op.create_index('uq_credit_product_versions_open', 'credit_product_versions', ['product_id'], unique=True, postgresql_where=sa.text("status = 'published' AND effective_to IS NULL"))
    op.create_table('credit_product_currencies',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.CheckConstraint('min_amount > 0 AND max_amount >= min_amount', name=op.f('ck_credit_product_currencies_amount_range_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'currency_code'], ['tenant_currencies.tenant_id', 'tenant_currencies.currency_code'], name='fk_credit_product_currencies_tenant_currency'),
    sa.ForeignKeyConstraint(['tenant_id', 'version_id'], ['credit_product_versions.tenant_id', 'credit_product_versions.id'], name='fk_credit_product_currencies_tenant_version'),
    sa.PrimaryKeyConstraint('version_id', 'currency_code', name=op.f('pk_credit_product_currencies'))
    )
    op.create_index(op.f('ix_credit_product_currencies_tenant_id'), 'credit_product_currencies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(VERSION_GUARD_FN)
    op.execute(VERSION_GUARD_TRIGGER)
    op.execute(CURRENCY_GUARD_FN)
    op.execute(CURRENCY_GUARD_TRIGGER)

    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": "tenant", "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, d, x in NEW_PERMISSIONS
    ])
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("INSERT INTO role_permissions (role_id, permission_id, granted_at) "
               "SELECT r.id, p.id, now() FROM roles r JOIN permissions p ON p.scope_kind = 'tenant' "
               "WHERE r.system_defined AND r.tenant_id IS NOT NULL AND p.code IN (" + codes + ") "
               "ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema (credit products, versions and snapshots created with the new structures are dropped)."""
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN (" + codes + "))")
    op.execute("DELETE FROM permissions WHERE code IN (" + codes + ")")
    op.execute("DROP TRIGGER IF EXISTS trg_credit_product_currencies_guard ON credit_product_currencies")
    op.execute("DROP TRIGGER IF EXISTS trg_credit_product_versions_guard ON credit_product_versions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_product_currencies_tenant_id'), table_name='credit_product_currencies')
    op.drop_table('credit_product_currencies')
    op.drop_index('uq_credit_product_versions_open', table_name='credit_product_versions', postgresql_where=sa.text("status = 'published' AND effective_to IS NULL"))
    op.drop_index(op.f('ix_credit_product_versions_tenant_id'), table_name='credit_product_versions')
    op.drop_index('ix_credit_product_versions_product', table_name='credit_product_versions')
    op.drop_table('credit_product_versions')
    op.drop_index(op.f('ix_credit_products_tenant_id'), table_name='credit_products')
    op.drop_table('credit_products')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS credit_product_currencies_guard()")
    op.execute("DROP FUNCTION IF EXISTS credit_product_versions_guard()")
