"""credit payment runtime

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-02 09:59:16.375022

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_PERMISSIONS = [
    ("payments.read", "Consultar pagos de prestamos y sus aplicaciones", False),
    ("payments.create", "Registrar pagos de prestamos (cobro en ventanilla o campo)", True),
]
# Guards and invariant triggers (copied from app.modules.loans.models so the migration is self-contained)
PAYMENT_FUNCTIONS = ["\nCREATE OR REPLACE FUNCTION credit_payment_sum_check() RETURNS trigger AS $$\nDECLARE v_id integer; v_amount numeric; v_sum numeric;\nBEGIN\n  IF TG_TABLE_NAME = 'credit_payments' THEN v_id := NEW.id; ELSE v_id := NEW.payment_id; END IF;\n  SELECT amount INTO v_amount FROM credit_payments WHERE id = v_id;\n  SELECT COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_applications WHERE payment_id = v_id;\n  IF v_amount IS NULL OR v_sum <> v_amount THEN\n    RAISE EXCEPTION 'credit payment % applications (%) must equal its amount (%)', v_id, v_sum, v_amount;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n", "\nCREATE OR REPLACE FUNCTION credit_payment_component_check() RETURNS trigger AS $$\nDECLARE v_due numeric; v_sum numeric;\nBEGIN\n  SELECT CASE NEW.component WHEN 'fee' THEN fees_due WHEN 'delinquency' THEN delinquency_due\n                            WHEN 'interest' THEN interest_due ELSE principal_due END\n    INTO v_due FROM credit_loan_obligations WHERE id = NEW.obligation_id FOR UPDATE;\n  SELECT COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_applications\n    WHERE obligation_id = NEW.obligation_id AND component = NEW.component;\n  IF v_sum > v_due THEN\n    RAISE EXCEPTION 'credit obligation % component % over-applied (% > %)', NEW.obligation_id, NEW.component, v_sum, v_due;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n"]
APPEND_ONLY_TABLES = ['credit_payments', 'credit_payment_applications']
CONSTRAINT_TRIGGERS = [('credit_payment_applications', 'trg_credit_payment_applications_sum', 'credit_payment_sum_check'), ('credit_payments', 'trg_credit_payments_sum', 'credit_payment_sum_check'), ('credit_payment_applications', 'trg_credit_payment_applications_component', 'credit_payment_component_check')]  # (table, trigger, function)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # must exist before the composite FKs that point at them
    op.create_unique_constraint('uq_credit_loan_obligations_tenant_id_loan', 'credit_loan_obligations', ['tenant_id', 'id', 'loan_id'])
    op.create_unique_constraint('uq_credit_loans_tenant_id_currency', 'credit_loans', ['tenant_id', 'id', 'currency_code'])
    op.create_table('credit_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('receiving_branch_id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=True),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('request_digest', sa.String(length=80), nullable=False),
    sa.Column('external_reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("((origin = 'counter') = (cash_session_id IS NOT NULL)) AND ((origin = 'counter') = (cash_movement_id IS NOT NULL))", name=op.f('ck_credit_payments_cash_matches_origin')),
    sa.CheckConstraint("method IN ('cash')", name=op.f('ck_credit_payments_method_valid')),
    sa.CheckConstraint("origin IN ('counter', 'field')", name=op.f('ck_credit_payments_origin_valid')),
    sa.CheckConstraint("status IN ('confirmed', 'pending', 'failed', 'reversed')", name=op.f('ck_credit_payments_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_payments_amount_positive')),
    sa.ForeignKeyConstraint(['cash_movement_id'], ['cash_movements.id'], name=op.f('fk_credit_payments_cash_movement_id_cash_movements')),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], name=op.f('fk_credit_payments_cash_session_id_cash_sessions')),
    sa.ForeignKeyConstraint(['tenant_id', 'loan_id', 'currency_code'], ['credit_loans.tenant_id', 'credit_loans.id', 'credit_loans.currency_code'], name='fk_credit_payments_loan_currency'),
    sa.ForeignKeyConstraint(['tenant_id', 'receiving_branch_id'], ['branches.company_id', 'branches.id'], name='fk_credit_payments_receiving_branch'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_payments_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_payments')),
    sa.UniqueConstraint('cash_movement_id', name='uq_credit_payments_cash_movement'),
    sa.UniqueConstraint('tenant_id', 'id', 'loan_id', name='uq_credit_payments_tenant_id_loan'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_credit_payments_tenant_key'),
    sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_credit_payments_tenant_number')
    )
    op.create_index('ix_credit_payments_loan', 'credit_payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_credit_payments_tenant_id'), 'credit_payments', ['tenant_id'], unique=False)
    op.create_index('uq_credit_payments_external_reference', 'credit_payments', ['tenant_id', 'method', 'external_reference'], unique=True, postgresql_where=sa.text('external_reference IS NOT NULL'))
    op.create_table('credit_payment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("component IN ('fee', 'delinquency', 'interest', 'principal')", name=op.f('ck_credit_payment_applications_component_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_payment_applications_amount_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'obligation_id', 'loan_id'], ['credit_loan_obligations.tenant_id', 'credit_loan_obligations.id', 'credit_loan_obligations.loan_id'], name='fk_credit_payment_applications_obligation'),
    sa.ForeignKeyConstraint(['tenant_id', 'payment_id', 'loan_id'], ['credit_payments.tenant_id', 'credit_payments.id', 'credit_payments.loan_id'], name='fk_credit_payment_applications_payment'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_payment_applications_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_payment_applications')),
    sa.UniqueConstraint('payment_id', 'obligation_id', 'component', name='uq_credit_payment_applications_row')
    )
    op.create_index('ix_credit_payment_applications_obligation', 'credit_payment_applications', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_credit_payment_applications_payment_id'), 'credit_payment_applications', ['payment_id'], unique=False)
    op.create_index(op.f('ix_credit_payment_applications_tenant_id'), 'credit_payment_applications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for fn_sql in PAYMENT_FUNCTIONS:
        op.execute(fn_sql)
    for table in APPEND_ONLY_TABLES:
        op.execute("CREATE TRIGGER trg_%s_guard BEFORE UPDATE OR DELETE ON %s FOR EACH ROW EXECUTE FUNCTION origination_append_only()" % (table, table))
    for table, trigger, fn in CONSTRAINT_TRIGGERS:
        op.execute("CREATE CONSTRAINT TRIGGER %s AFTER INSERT ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION %s()" % (trigger, table, fn))

    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": "tenant", "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, d, x in NEW_PERMISSIONS
    ])
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("INSERT INTO role_permissions (role_id, permission_id, granted_at) "
               "SELECT r.id, p.id, now() FROM roles r JOIN permissions p ON p.scope_kind = 'tenant' "
               "WHERE r.system_defined AND r.tenant_id IS NOT NULL AND p.code IN (" + codes + ") "
               "ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema (payments and applications created with the new structures are dropped; the cash movements they
    made (counter payments) stay in the cash ledger, which this package does not own: no economic reversal is invented)."""
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN (" + codes + "))")
    op.execute("DELETE FROM permissions WHERE code IN (" + codes + ")")
    for table, trigger, _fn in CONSTRAINT_TRIGGERS:
        op.execute("DROP TRIGGER IF EXISTS %s ON %s" % (trigger, table))
    for table in APPEND_ONLY_TABLES:
        op.execute("DROP TRIGGER IF EXISTS trg_%s_guard ON %s" % (table, table))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_payment_applications_tenant_id'), table_name='credit_payment_applications')
    op.drop_index(op.f('ix_credit_payment_applications_payment_id'), table_name='credit_payment_applications')
    op.drop_index('ix_credit_payment_applications_obligation', table_name='credit_payment_applications')
    op.drop_table('credit_payment_applications')
    op.drop_index('uq_credit_payments_external_reference', table_name='credit_payments', postgresql_where=sa.text('external_reference IS NOT NULL'))
    op.drop_index(op.f('ix_credit_payments_tenant_id'), table_name='credit_payments')
    op.drop_index('ix_credit_payments_loan', table_name='credit_payments')
    op.drop_table('credit_payments')
    op.drop_constraint('uq_credit_loans_tenant_id_currency', 'credit_loans', type_='unique')
    op.drop_constraint('uq_credit_loan_obligations_tenant_id_loan', 'credit_loan_obligations', type_='unique')
    # ### end Alembic commands ###
    for fn_name in ("credit_payment_sum_check", "credit_payment_component_check"):
        op.execute("DROP FUNCTION IF EXISTS %s()" % fn_name)
    # ### end Alembic commands ###
