"""credit payment reversal

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-02 13:25:19.279273

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_PERMISSIONS = [("payments.reverse", "Revertir por completo un pago de prestamo (sale efectivo en cobros de ventanilla)", True)]
# Functions and triggers (copied from app.modules.loans.models so the migration is self-contained)
REVERSAL_FUNCTIONS = ["\nCREATE OR REPLACE FUNCTION credit_reversal_sum_check() RETURNS trigger AS $$\nDECLARE v_id integer; v_amount numeric; v_sum numeric;\nBEGIN\n  IF TG_TABLE_NAME = 'credit_payment_reversals' THEN v_id := NEW.id; ELSE v_id := NEW.reversal_id; END IF;\n  SELECT amount INTO v_amount FROM credit_payment_reversals WHERE id = v_id;\n  SELECT COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_reversal_applications WHERE reversal_id = v_id;\n  IF v_amount IS NULL OR v_sum <> v_amount THEN\n    RAISE EXCEPTION 'credit payment reversal % applications (%) must equal its amount (%)', v_id, v_sum, v_amount;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n", "\nCREATE OR REPLACE FUNCTION credit_reversal_cash_check() RETURNS trigger AS $$\nDECLARE v_receipt integer; m_kind text; m_amount numeric; m_session integer; m_reverses integer;\nBEGIN\n  IF NEW.origin = 'counter' THEN\n    SELECT cash_movement_id INTO v_receipt FROM credit_payments WHERE id = NEW.payment_id;\n    SELECT kind, amount, session_id, reverses_id INTO m_kind, m_amount, m_session, m_reverses\n      FROM cash_movements WHERE id = NEW.cash_movement_id;\n    IF m_kind IS DISTINCT FROM 'credit_payment_reversal' OR m_amount IS DISTINCT FROM -NEW.amount\n       OR m_session IS DISTINCT FROM NEW.cash_session_id OR m_reverses IS DISTINCT FROM v_receipt THEN\n      RAISE EXCEPTION 'credit payment reversal % is not backed by its compensating cash movement', NEW.id;\n    END IF;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n"]
NET_COMPONENT_FN = "\nCREATE OR REPLACE FUNCTION credit_payment_component_check() RETURNS trigger AS $$\nDECLARE v_due numeric; v_sum numeric;\nBEGIN\n  SELECT CASE NEW.component WHEN 'fee' THEN fees_due WHEN 'delinquency' THEN delinquency_due\n                            WHEN 'interest' THEN interest_due ELSE principal_due END\n    INTO v_due FROM credit_loan_obligations WHERE id = NEW.obligation_id FOR UPDATE;\n  SELECT COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_applications\n    WHERE obligation_id = NEW.obligation_id AND component = NEW.component;\n  SELECT v_sum - COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_reversal_applications\n    WHERE obligation_id = NEW.obligation_id AND component = NEW.component;\n  IF v_sum > v_due THEN\n    RAISE EXCEPTION 'credit obligation % component % over-applied (% > %)', NEW.obligation_id, NEW.component, v_sum, v_due;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n"  # T-009: over-application is checked on the NET sum
GROSS_COMPONENT_FN = "\nCREATE OR REPLACE FUNCTION credit_payment_component_check() RETURNS trigger AS $$\nDECLARE v_due numeric; v_sum numeric;\nBEGIN\n  SELECT CASE NEW.component WHEN 'fee' THEN fees_due WHEN 'delinquency' THEN delinquency_due\n                            WHEN 'interest' THEN interest_due ELSE principal_due END\n    INTO v_due FROM credit_loan_obligations WHERE id = NEW.obligation_id FOR UPDATE;\n  SELECT COALESCE(SUM(amount), 0) INTO v_sum FROM credit_payment_applications\n    WHERE obligation_id = NEW.obligation_id AND component = NEW.component;\n  IF v_sum > v_due THEN\n    RAISE EXCEPTION 'credit obligation % component % over-applied (% > %)', NEW.obligation_id, NEW.component, v_sum, v_due;\n  END IF;\n  RETURN NULL;\nEND $$ LANGUAGE plpgsql\n"  # the 0010 version, restored on downgrade
APPEND_ONLY_TABLES = ["credit_payment_reversals", "credit_payment_reversal_applications"]
CONSTRAINT_TRIGGERS = [('credit_payment_reversal_applications', 'trg_credit_payment_reversal_applications_sum', 'credit_reversal_sum_check'), ('credit_payment_reversals', 'trg_credit_payment_reversals_sum', 'credit_reversal_sum_check'), ('credit_payment_reversals', 'trg_credit_payment_reversals_cash', 'credit_reversal_cash_check')]  # (table, trigger, function)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # FK targets must exist before the tables that point at them
    op.create_unique_constraint('uq_credit_payment_applications_mirror', 'credit_payment_applications', ['tenant_id', 'id', 'payment_id', 'obligation_id', 'loan_id', 'component', 'amount'])
    op.create_unique_constraint('uq_credit_payments_reversal_target', 'credit_payments', ['tenant_id', 'id', 'loan_id', 'amount', 'origin', 'currency_code', 'receiving_branch_id'])
    op.create_table('credit_payment_reversals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('reversal_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('reversed_by', sa.Integer(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('reversal_branch_id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=True),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('request_digest', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("((origin = 'counter') = (cash_session_id IS NOT NULL)) AND ((origin = 'counter') = (cash_movement_id IS NOT NULL))", name=op.f('ck_credit_payment_reversals_cash_matches_origin')),
    sa.CheckConstraint("origin IN ('counter', 'field')", name=op.f('ck_credit_payment_reversals_origin_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_payment_reversals_amount_positive')),
    sa.CheckConstraint('char_length(btrim(reason)) BETWEEN 3 AND 500', name=op.f('ck_credit_payment_reversals_reason_length')),
    sa.ForeignKeyConstraint(['cash_movement_id'], ['cash_movements.id'], name=op.f('fk_credit_payment_reversals_cash_movement_id_cash_movements')),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], name=op.f('fk_credit_payment_reversals_cash_session_id_cash_sessions')),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], name=op.f('fk_credit_payment_reversals_reversed_by_users')),
    sa.ForeignKeyConstraint(['tenant_id', 'payment_id', 'loan_id', 'amount', 'origin', 'currency_code', 'reversal_branch_id'], ['credit_payments.tenant_id', 'credit_payments.id', 'credit_payments.loan_id', 'credit_payments.amount', 'credit_payments.origin', 'credit_payments.currency_code', 'credit_payments.receiving_branch_id'], name='fk_credit_payment_reversals_payment'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_payment_reversals_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_payment_reversals')),
    sa.UniqueConstraint('cash_movement_id', name='uq_credit_payment_reversals_cash_movement'),
    sa.UniqueConstraint('payment_id', name='uq_credit_payment_reversals_payment'),
    sa.UniqueConstraint('tenant_id', 'id', 'payment_id', 'loan_id', name='uq_credit_payment_reversals_tenant_id_payment'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_credit_payment_reversals_tenant_key'),
    sa.UniqueConstraint('tenant_id', 'reversal_number', name='uq_credit_payment_reversals_tenant_number')
    )
    op.create_index('ix_credit_payment_reversals_loan', 'credit_payment_reversals', ['loan_id'], unique=False)
    op.create_index(op.f('ix_credit_payment_reversals_tenant_id'), 'credit_payment_reversals', ['tenant_id'], unique=False)
    op.create_table('credit_payment_reversal_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reversal_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('original_application_id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("component IN ('fee', 'delinquency', 'interest', 'principal')", name=op.f('ck_credit_payment_reversal_applications_component_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_payment_reversal_applications_amount_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'original_application_id', 'payment_id', 'obligation_id', 'loan_id', 'component', 'amount'], ['credit_payment_applications.tenant_id', 'credit_payment_applications.id', 'credit_payment_applications.payment_id', 'credit_payment_applications.obligation_id', 'credit_payment_applications.loan_id', 'credit_payment_applications.component', 'credit_payment_applications.amount'], name='fk_credit_payment_reversal_applications_original'),
    sa.ForeignKeyConstraint(['tenant_id', 'reversal_id', 'payment_id', 'loan_id'], ['credit_payment_reversals.tenant_id', 'credit_payment_reversals.id', 'credit_payment_reversals.payment_id', 'credit_payment_reversals.loan_id'], name='fk_credit_payment_reversal_applications_reversal'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_payment_reversal_applications_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_payment_reversal_applications')),
    sa.UniqueConstraint('original_application_id', name='uq_credit_payment_reversal_applications_original')
    )
    op.create_index('ix_credit_payment_reversal_applications_obligation', 'credit_payment_reversal_applications', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_credit_payment_reversal_applications_reversal_id'), 'credit_payment_reversal_applications', ['reversal_id'], unique=False)
    op.create_index(op.f('ix_credit_payment_reversal_applications_tenant_id'), 'credit_payment_reversal_applications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    for fn_sql in REVERSAL_FUNCTIONS:
        op.execute(fn_sql)
    op.execute(NET_COMPONENT_FN)
    for table in APPEND_ONLY_TABLES:
        op.execute("CREATE TRIGGER trg_%s_guard BEFORE UPDATE OR DELETE ON %s FOR EACH ROW EXECUTE FUNCTION origination_append_only()" % (table, table))
    for table, trigger, fn in CONSTRAINT_TRIGGERS:
        op.execute("CREATE CONSTRAINT TRIGGER %s AFTER INSERT ON %s DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION %s()" % (trigger, table, fn))

    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": "tenant", "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, d, x in NEW_PERMISSIONS
    ])
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("INSERT INTO role_permissions (role_id, permission_id, granted_at) "
               "SELECT r.id, p.id, now() FROM roles r JOIN permissions p ON p.scope_kind = 'tenant' "
               "WHERE r.system_defined AND r.tenant_id IS NOT NULL AND p.code IN (" + codes + ") "
               "ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema.

    REFUSES to run when real reversals exist: dropping them would silently make economically reversed payments look applied
    again while the compensating cash movements stay in the cash ledger (which this package does not own). On a database
    without reversals it is a clean downgrade."""
    bind = op.get_bind()
    if bind.execute(sa.text("SELECT EXISTS (SELECT 1 FROM credit_payment_reversals)")).scalar():
        raise RuntimeError(
            "Cannot downgrade 0011: credit_payment_reversals contains economic history. "
            "Dropping it would falsify the payment ledger; restore from backup or keep revision 0011."
        )
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN (" + codes + "))")
    op.execute("DELETE FROM permissions WHERE code IN (" + codes + ")")
    for table, trigger, _fn in CONSTRAINT_TRIGGERS:
        op.execute("DROP TRIGGER IF EXISTS %s ON %s" % (trigger, table))
    for table in APPEND_ONLY_TABLES:
        op.execute("DROP TRIGGER IF EXISTS trg_%s_guard ON %s" % (table, table))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_payment_reversal_applications_tenant_id'), table_name='credit_payment_reversal_applications')
    op.drop_index(op.f('ix_credit_payment_reversal_applications_reversal_id'), table_name='credit_payment_reversal_applications')
    op.drop_index('ix_credit_payment_reversal_applications_obligation', table_name='credit_payment_reversal_applications')
    op.drop_table('credit_payment_reversal_applications')
    op.drop_index(op.f('ix_credit_payment_reversals_tenant_id'), table_name='credit_payment_reversals')
    op.drop_index('ix_credit_payment_reversals_loan', table_name='credit_payment_reversals')
    op.drop_table('credit_payment_reversals')
    op.drop_constraint('uq_credit_payments_reversal_target', 'credit_payments', type_='unique')
    op.drop_constraint('uq_credit_payment_applications_mirror', 'credit_payment_applications', type_='unique')
    # ### end Alembic commands ###
    op.execute(GROSS_COMPONENT_FN)
    for fn_name in ("credit_reversal_sum_check", "credit_reversal_cash_check"):
        op.execute("DROP FUNCTION IF EXISTS %s()" % fn_name)
