"""credit collection assignment

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-02 23:32:33.190250

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NEW_PERMISSIONS = [("collections.assign", "Asignar, reasignar y terminar la responsabilidad de cobranza de un prestamo (no concede acceso)", True)]
# Functions and triggers (copied from app.modules.loans.models so the migration is self-contained)
ASSIGNMENT_FUNCTIONS = ["\nCREATE OR REPLACE FUNCTION credit_collection_assignments_guard() RETURNS trigger AS $$\nBEGIN\n  IF TG_OP = 'DELETE' THEN\n    RAISE EXCEPTION 'collection assignment % cannot be deleted: it is history', OLD.id;\n  END IF;\n  IF OLD.ended_at IS NOT NULL THEN\n    RAISE EXCEPTION 'collection assignment % is closed: history is immutable', OLD.id;\n  END IF;\n  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id\n     OR NEW.loan_id IS DISTINCT FROM OLD.loan_id OR NEW.assignee_user_id IS DISTINCT FROM OLD.assignee_user_id\n     OR NEW.managing_branch_id IS DISTINCT FROM OLD.managing_branch_id OR NEW.assigned_by IS DISTINCT FROM OLD.assigned_by\n     OR NEW.assigned_at IS DISTINCT FROM OLD.assigned_at OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key\n     OR NEW.request_digest IS DISTINCT FROM OLD.request_digest THEN\n    RAISE EXCEPTION 'collection assignment % is immutable: only its single end transition may change', OLD.id;\n  END IF;\n  IF NEW.ended_at IS NULL THEN\n    RAISE EXCEPTION 'collection assignment % is open: the only allowed change is to close it', OLD.id;\n  END IF;\n  RETURN NEW;\nEND $$ LANGUAGE plpgsql\n", "\nCREATE OR REPLACE FUNCTION credit_collection_assignments_insert_check() RETURNS trigger AS $$\nBEGIN\n  IF NEW.ended_at IS NOT NULL THEN\n    RAISE EXCEPTION 'a collection assignment is born open: it cannot be inserted already closed';\n  END IF;\n  IF NEW.managing_branch_id IS DISTINCT FROM\n     (SELECT managing_branch_id FROM credit_loans WHERE id = NEW.loan_id AND tenant_id = NEW.tenant_id) THEN\n    RAISE EXCEPTION 'collection assignment managing branch must be the loan''s own managing branch';\n  END IF;\n  RETURN NEW;\nEND $$ LANGUAGE plpgsql\n"]
ASSIGNMENT_TRIGGERS = ['CREATE TRIGGER trg_credit_collection_assignments_insert_check BEFORE INSERT ON credit_collection_assignments FOR EACH ROW EXECUTE FUNCTION credit_collection_assignments_insert_check()', 'CREATE TRIGGER trg_credit_collection_assignments_guard BEFORE UPDATE OR DELETE ON credit_collection_assignments FOR EACH ROW EXECUTE FUNCTION credit_collection_assignments_guard()']


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # the composite FKs of the new table need this UNIQUE target on users (id is already globally unique)
    op.create_unique_constraint('uq_users_tenant_id', 'users', ['company_id', 'id'])
    op.create_table('credit_collection_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=False),
    sa.Column('managing_branch_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('request_digest', sa.String(length=80), nullable=False),
    sa.Column('ended_by', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('end_request_digest', sa.String(length=80), nullable=True),
    sa.CheckConstraint('(ended_at IS NULL) = (ended_by IS NULL) AND (ended_at IS NULL) = (end_idempotency_key IS NULL) AND (ended_at IS NULL) = (end_request_digest IS NULL)', name=op.f('ck_credit_collection_assignments_end_fields_together')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= assigned_at', name=op.f('ck_credit_collection_assignments_end_not_before_start')),
    sa.ForeignKeyConstraint(['tenant_id', 'assigned_by'], ['users.company_id', 'users.id'], name='fk_credit_collection_assignments_assigned_by'),
    sa.ForeignKeyConstraint(['tenant_id', 'assignee_user_id'], ['users.company_id', 'users.id'], name='fk_credit_collection_assignments_assignee'),
    sa.ForeignKeyConstraint(['tenant_id', 'ended_by'], ['users.company_id', 'users.id'], name='fk_credit_collection_assignments_ended_by'),
    sa.ForeignKeyConstraint(['tenant_id', 'loan_id'], ['credit_loans.tenant_id', 'credit_loans.id'], name='fk_credit_collection_assignments_loan'),
    sa.ForeignKeyConstraint(['tenant_id', 'managing_branch_id'], ['branches.company_id', 'branches.id'], name='fk_credit_collection_assignments_branch'),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], name=op.f('fk_credit_collection_assignments_tenant_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_collection_assignments')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_credit_collection_assignments_tenant_key')
    )
    op.create_index('ix_credit_collection_assignments_loan', 'credit_collection_assignments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_credit_collection_assignments_tenant_id'), 'credit_collection_assignments', ['tenant_id'], unique=False)
    op.create_index('uq_credit_collection_assignments_end_key', 'credit_collection_assignments', ['tenant_id', 'end_idempotency_key'], unique=True, postgresql_where=sa.text('end_idempotency_key IS NOT NULL'))
    op.create_index('uq_credit_collection_assignments_open', 'credit_collection_assignments', ['tenant_id', 'loan_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###
    for fn_sql in ASSIGNMENT_FUNCTIONS:
        op.execute(fn_sql)
    for trigger_sql in ASSIGNMENT_TRIGGERS:
        op.execute(trigger_sql)

    permissions = sa.table("permissions", sa.column("code", sa.String), sa.column("description", sa.String),
                           sa.column("scope_kind", sa.String), sa.column("is_sensitive", sa.Boolean),
                           sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(permissions, [
        {"code": c, "description": d, "scope_kind": "tenant", "is_sensitive": x, "created_at": datetime.now(timezone.utc)}
        for c, d, x in NEW_PERMISSIONS
    ])
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("INSERT INTO role_permissions (role_id, permission_id, granted_at) "
               "SELECT r.id, p.id, now() FROM roles r JOIN permissions p ON p.scope_kind = 'tenant' "
               "WHERE r.system_defined AND r.tenant_id IS NOT NULL AND p.code IN (" + codes + ") "
               "ON CONFLICT DO NOTHING")


def downgrade() -> None:
    """Downgrade schema.

    REFUSES to run when any assignment history exists: dropping the table would silently erase operational history
    (who was responsible for which loan, and when). On a database without assignments it is a clean downgrade."""
    bind = op.get_bind()
    if bind.execute(sa.text("SELECT EXISTS (SELECT 1 FROM credit_collection_assignments)")).scalar():
        raise RuntimeError(
            "Cannot downgrade 0014: credit_collection_assignments contains operational history. "
            "Dropping it would erase who was responsible for each loan; keep revision 0014 or restore from backup."
        )
    codes = ", ".join("'%s'" % c for c, *_ in NEW_PERMISSIONS)
    op.execute("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN (" + codes + "))")
    op.execute("DELETE FROM permissions WHERE code IN (" + codes + ")")
    op.execute("DROP TRIGGER IF EXISTS trg_credit_collection_assignments_insert_check ON credit_collection_assignments")
    op.execute("DROP TRIGGER IF EXISTS trg_credit_collection_assignments_guard ON credit_collection_assignments")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_credit_collection_assignments_open', table_name='credit_collection_assignments', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('uq_credit_collection_assignments_end_key', table_name='credit_collection_assignments', postgresql_where=sa.text('end_idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_credit_collection_assignments_tenant_id'), table_name='credit_collection_assignments')
    op.drop_index('ix_credit_collection_assignments_loan', table_name='credit_collection_assignments')
    op.drop_table('credit_collection_assignments')
    op.drop_constraint('uq_users_tenant_id', 'users', type_='unique')
    # ### end Alembic commands ###
    for fn_name in ("credit_collection_assignments_guard", "credit_collection_assignments_insert_check"):
        op.execute("DROP FUNCTION IF EXISTS %s()" % fn_name)
