"""Collection assignment (T-012): WHO is responsible for collecting ONE loan, as effective-dated history.

* Target = the loan. At most ONE open row per loan (``ended_at IS NULL``): database partial UNIQUE + the loan lock.
* Identity = ``users`` (never the legacy ``role = 'collector'``, ``customers.assigned_collector_id`` or ``routes``).
* History is never rewritten: a reassignment closes the open row and inserts a new one in the same transaction; ``end``
  only closes. No row is deleted, reopened or edited (database guard).
* Assignment is metadata: it grants NO access, moves no money and never touches the loan status, the ledger, payments,
  reversals or the delinquency assessment (nothing closes or revives a row automatically: only ``end`` does).
* Only a loan stored ``active`` or ``past_due`` can receive a NEW assignment (lifecycle gate, not an overdue test);
  ``end`` is allowed in any status so that responsibility can always be closed.
* Authorization: ``collections.assign`` (writes) / ``collections.read`` (reads) on the loan's MANAGING branch; a loan without
  one needs a tenant-level grant. The assignee must be an ``active`` user of the tenant holding ``collections.read`` that
  covers the loan (tenant-level for a loan without managing branch). Eligibility is checked at command time only.
* Idempotency: ``(tenant, idempotency_key)`` + digest for assign/reassign (stored on the new row), and a separate
  ``(tenant, end_idempotency_key)`` + digest for ``end``. Same key and digest -> replay (no write, no audit); same key and
  another digest -> 409. A NEW key that asks for the current assignee is 409 ``already_assigned`` (never a silent no-op).
* Lock order: 1. loan row ``FOR UPDATE``  2. the open assignment row  3. assignee lookup. No Cash, no obligations.
* Dates are generated by the server (no backdating, no future assignment). No reason field in v1.
"""

import hashlib

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.core.errors import IdempotencyConflict
from app.core.time import now_utc
from app.modules.credit.rules import canonical_json
from app.modules.identity.audit import record_event
from app.modules.identity.authorization import Principal, build_principal
from app.modules.identity.errors import PermissionDenied, TenantMismatch
from app.modules.identity.models import UserAccount
from app.modules.loans.assignment_schemas import AssignIn, EndAssignmentIn
from app.modules.loans.errors import (
    AlreadyAssigned,
    AssigneeNotEligible,
    AssignmentInvariantViolation,
    LoanNotAssignable,
    NoActiveAssignment,
)
from app.modules.loans.models import CreditCollectionAssignment, CreditLoan
from app.modules.loans.payments import _gate_tenant

ASSIGN, READ = "collections.assign", "collections.read"
ASSIGNABLE_STATUSES = ("active", "past_due")


def _covers(principal: Principal, permission: str, loan: CreditLoan) -> bool:
    """The loan's MANAGING branch is the boundary; without one, a tenant-level grant is required. Origin, disbursement and
    receiving branches never substitute it."""
    if loan.managing_branch_id is None:
        return principal.holds_at_tenant_scope(permission)
    return principal.holds_for_branch(permission, loan.managing_branch_id)


def _digest(payload: dict) -> str:
    return "sha256:" + hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()


def _assign_digest(loan_id: int, assignee_user_id: int) -> str:
    return _digest({"operation": "assign", "loan_id": loan_id, "assignee_user_id": assignee_user_id})


def _end_digest(loan_id: int, assignment_id: int) -> str:
    return _digest({"operation": "end_assignment", "loan_id": loan_id, "assignment_id": assignment_id})


def _out(a: CreditCollectionAssignment) -> dict:
    """IDs only: no names, contact data, role strings, keys or digests."""
    return {
        "assignment_id": a.id,
        "loan_id": a.loan_id,
        "assignee_user_id": a.assignee_user_id,
        "managing_branch_id": a.managing_branch_id,
        "assigned_by": a.assigned_by,
        "assigned_at": a.assigned_at,
        "ended_by": a.ended_by,
        "ended_at": a.ended_at,
        "current": a.ended_at is None,
    }


def _locked_loan(db: Session, actor: Principal, loan_id: int) -> CreditLoan:
    loan = db.scalar(
        select(CreditLoan)
        .where(CreditLoan.id == loan_id, CreditLoan.tenant_id == actor.tenant_id)  # a foreign loan is a 404
        .with_for_update()
        .execution_options(populate_existing=True)
    )
    if loan is None:
        raise TenantMismatch()
    return loan


def _open(db: Session, loan_id: int, *, lock: bool) -> CreditCollectionAssignment | None:
    stmt = select(CreditCollectionAssignment).where(
        CreditCollectionAssignment.loan_id == loan_id, CreditCollectionAssignment.ended_at.is_(None)
    )
    if lock:
        stmt = stmt.with_for_update().execution_options(populate_existing=True)
    return db.scalar(stmt)


def _eligible(db: Session, actor: Principal, loan: CreditLoan, user_id: int) -> UserAccount:
    user = db.get(UserAccount, user_id)
    if user is None or user.company_id != actor.tenant_id:
        raise TenantMismatch()  # another tenant's user is a 404
    if user.status != "active":
        raise AssigneeNotEligible()
    if not _covers(build_principal(db, user, 0), READ, loan):  # modern RBAC, never the legacy role string
        raise AssigneeNotEligible()
    return user


# --- commands ----------------------------------------------------------------------------------------
def assign(db: Session, actor: Principal, loan_id: int, body: AssignIn, client_ip: str | None) -> dict:
    _gate_tenant(actor)
    loan = _locked_loan(db, actor, loan_id)  # 1. loan first
    if not _covers(actor, ASSIGN, loan):
        raise PermissionDenied()
    digest = _assign_digest(loan.id, body.assignee_user_id)
    prior = db.scalar(
        select(CreditCollectionAssignment).where(
            CreditCollectionAssignment.tenant_id == actor.tenant_id,
            CreditCollectionAssignment.idempotency_key == body.idempotency_key,
        )
    )
    if prior is not None:  # decided under the loan lock; the UNIQUE constraint is the database backstop
        if prior.request_digest == digest and prior.loan_id == loan.id:
            return {**_out(prior), "replayed": True}
        raise IdempotencyConflict()
    if loan.status not in ASSIGNABLE_STATUSES:  # lifecycle gate (the stored status is NOT an overdue test)
        raise LoanNotAssignable()
    active = _open(db, loan.id, lock=True)  # 2. the open row
    assignee = _eligible(db, actor, loan, body.assignee_user_id)  # 3. eligibility at command time
    if active is not None and active.assignee_user_id == assignee.id:
        raise AlreadyAssigned()  # a NEW key never produces a hidden no-op: its key would not be persisted
    now = now_utc()
    if active is not None:  # reassignment: close the old row (history stays), then insert the new one
        active.ended_by, active.ended_at = actor.user_id, now
        active.end_idempotency_key, active.end_request_digest = body.idempotency_key, digest
        db.flush()
    row = CreditCollectionAssignment(
        tenant_id=actor.tenant_id,
        loan_id=loan.id,
        assignee_user_id=assignee.id,
        managing_branch_id=loan.managing_branch_id,  # snapshot of the loan's, never from the client
        assigned_by=actor.user_id,
        assigned_at=now,
        idempotency_key=body.idempotency_key,
        request_digest=digest,
    )
    db.add(row)
    try:
        db.flush()
    except IntegrityError as exc:
        db.rollback()
        raise (IdempotencyConflict() if "idempotency" in str(exc.orig) else AssignmentInvariantViolation()) from None
    record_event(
        db,
        "loan.collection_reassigned" if active is not None else "loan.collection_assigned",
        tenant_id=actor.tenant_id,
        actor_id=actor.user_id,
        client_ip=client_ip,
        details={
            "assignment_id": row.id,
            "loan_id": loan.id,
            "loan_number": loan.loan_number,
            "assignee_user_id": assignee.id,
            "previous_assignee_user_id": active.assignee_user_id if active else None,
            "previous_assignment_id": active.id if active else None,
            "managing_branch_id": loan.managing_branch_id,
        },
    )
    db.commit()
    return {**_out(row), "replayed": False}


def end(db: Session, actor: Principal, loan_id: int, body: EndAssignmentIn, client_ip: str | None) -> dict:
    _gate_tenant(actor)
    loan = _locked_loan(db, actor, loan_id)  # 1. loan first
    if not _covers(actor, ASSIGN, loan):
        raise PermissionDenied()
    prior = db.scalar(
        select(CreditCollectionAssignment).where(
            CreditCollectionAssignment.tenant_id == actor.tenant_id,
            CreditCollectionAssignment.end_idempotency_key == body.idempotency_key,
        )
    )
    if prior is not None:
        if prior.loan_id == loan.id and prior.end_request_digest == _end_digest(loan.id, prior.id):
            return {**_out(prior), "replayed": True}  # the very same end command, retried
        raise IdempotencyConflict()
    active = _open(db, loan.id, lock=True)  # 2. the open row (any loan status: closing must always be possible)
    if active is None:
        raise NoActiveAssignment()  # never a silent success on a stale command
    active.ended_by, active.ended_at = actor.user_id, now_utc()
    active.end_idempotency_key, active.end_request_digest = body.idempotency_key, _end_digest(loan.id, active.id)
    try:
        db.flush()
    except IntegrityError:
        db.rollback()
        raise AssignmentInvariantViolation() from None
    record_event(
        db,
        "loan.collection_assignment_ended",
        tenant_id=actor.tenant_id,
        actor_id=actor.user_id,
        client_ip=client_ip,
        details={
            "assignment_id": active.id,
            "loan_id": loan.id,
            "loan_number": loan.loan_number,
            "assignee_user_id": active.assignee_user_id,
            "managing_branch_id": loan.managing_branch_id,
        },
    )
    db.commit()
    return {**_out(active), "replayed": False}


# --- reads (collections.read, same boundary as the T-011 worklist; pure) --------------------------------
def _readable_loan(db: Session, actor: Principal, loan_id: int) -> CreditLoan:
    _gate_tenant(actor)
    loan = db.scalar(select(CreditLoan).where(CreditLoan.id == loan_id, CreditLoan.tenant_id == actor.tenant_id))
    if loan is None:
        raise TenantMismatch()
    if not _covers(actor, READ, loan):  # being the assignee does NOT grant access
        raise PermissionDenied()
    return loan


def get_current(db: Session, actor: Principal, loan_id: int) -> dict:
    loan = _readable_loan(db, actor, loan_id)
    row = _open(db, loan.id, lock=False)
    return {"loan_id": loan.id, "assignment": _out(row) if row else None}  # unassigned is a normal state: 200 + null


def get_history(db: Session, actor: Principal, loan_id: int) -> dict:
    loan = _readable_loan(db, actor, loan_id)
    rows = db.scalars(
        select(CreditCollectionAssignment)
        .where(CreditCollectionAssignment.loan_id == loan.id)
        .order_by(CreditCollectionAssignment.assigned_at, CreditCollectionAssignment.id)
    ).all()
    return {"loan_id": loan.id, "assignments": [_out(r) for r in rows]}
